const BlockchainActionTypes = {
  CONNECTION_REQUEST: "CONNECTION_REQUEST",
  CONNECTION_SUCCESS: "CONNECTION_SUCCESS",
  CONNECTION_FAILED: "CONNECTION_FAILED",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",

  BALANCE_REQUEST: "BALANCE_REQUEST",
  BALANCE_SUCCESS: "BALANCE_SUCCESS",
  BALANCE_FAILED: "BALANCE_FAILED",
};

export default BlockchainActionTypes;
