const MarketplaceActionTypes = {
  SET_SWORD_MARKETPLACE: "SET_SWORD_MARKETPLACE",

  FETCH_LISTED_REQUEST: "FETCH_LISTED_REQUEST",
  FETCH_LISTED_SUCCESS: "FETCH_LISTED_SUCCESS",
  FETCH_LISTED_FAILED: "FETCH_LISTED_FAILED",

  FETCH_PURCHASED_REQUEST: "FETCH_PURCHASED_REQUEST",
  FETCH_PURCHASED_SUCCESS: "FETCH_PURCHASED_SUCCESS",
  FETCH_PURCHASED_FAILED: "FETCH_PURCHASED_FAILED",

  FETCH_MARKET_REQUEST: "FETCH_MARKET_REQUEST",
  FETCH_MARKET_SUCCESS: "FETCH_MARKET_SUCCESS",
  FETCH_MARKET_FAILED: "FETCH_MARKET_FAILED",

  PURCHASE_ITEM_REQUEST: "PURCHASE_ITEM_REQUEST",
  PURCHASE_ITEM_SUCCESS: "PURCHASE_ITEM_SUCCESS",
  PURCHASE_ITEM_FAILED: "PURCHASE_ITEM_FAILED",

  WITHDRAW_ITEM_REQUEST: "WITHDRAW_ITEM_REQUEST",
  WITHDRAW_ITEM_SUCCESS: "WITHDRAW_ITEM_SUCCESS",
  WITHDRAW_ITEM_FAILED: "WITHDRAW_ITEM_FAILED",

  LIST_ITEM_REQUEST: "LIST_ITEM_REQUEST",
  LIST_ITEM_SUCCESS: "LIST_ITEM_SUCCESS",
  LIST_ITEM_FAILED: "LIST_ITEM_FAILED",
};

export default MarketplaceActionTypes;
