const BattleActionTypes = {
  SET_BATTLE_LOG_ACTIVE: "SET_BATTLE_LOG_ACTIVE",
  SET_BATTLE_LOG: "SET_BATTLE_LOG",
  CLEAR_BATTLE_LOG: "CLEAR_BATTLE_LOG",
  SET_SWORD: "SET_SWORD",
  BATTLE_REQUEST: "BATTLE_REQUEST",
  BATTLE_SUCCESS: "BATTLE_SUCCESS",
  BATTLE_FAILED: "BATTLE_FAILED",
};

export default BattleActionTypes;
