const TransferActionTypes = {
  SET_SWORD_TRANSFER: "SET_SWORD_TRANSFER",
  TRANSFER_REQUEST: "TRANSFER_REQUEST",
  TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
  TRANSFER_FAILED: "TRANSFER_FAILED",
};

export default TransferActionTypes;
