const MergeActionTypes = {
  SET_SWORD_1: "SET_SWORD_1",
  SET_SWORD_2: "SET_SWORD_2",
  MERGE_REQUEST: "MERGE_REQUEST",
  MERGE_SUCCESS: "MERGE_SUCCESS",
  MERGE_FAILED: "MERGE_FAILED",
  SET_NEW_ITEM_ACTIVE: "SET_NEW_ITEM_ACTIVE",
};

export default MergeActionTypes;
